tunnel: 24a1d203-b94d-422e-aaad-a4b1ddd6be86
credentials-file: /home/ubuntu/projects/cv-site/deploy/cloudflare-credentials.json
ingress:
  - hostname: faztrick.com
    service: http://127.0.0.1:18090
  - hostname: www.faztrick.com
    service: http://127.0.0.1:18090
  - service: http_status:404
